# Generated by Django 4.2.6 on 2023-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
