# Generated by Django 4.2.7 on 2023-11-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="orderId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.order",
            ),
        ),
    ]
