# Generated by Django 4.2.7 on 2023-11-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_order_totalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
