# Generated by Django 4.2.7 on 2023-11-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0007_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
