# Generated by Django 4.2.7 on 2023-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0008_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.CharField(default="", max_length=200),
        ),
    ]
