# Generated by Django 4.2.7 on 2023-11-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0009_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.IntegerField(default=1),
        ),
    ]
