# Generated by Django 4.2.7 on 2023-11-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0010_alter_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.category",
            ),
        ),
    ]
